ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
    security:
        ssl:
            keyStore: keystore.jks
            keyAlias: sampleAlias
            keyStorePassword: foobar
            privateKeyPassword: foobar
